# my global config
#
global:
#  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
#  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
   scrape_interval: 4m
   scrape_timeout: 2m

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    scrape_interval: 1m

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']

  # node exporter on localhost
  - job_name: 'node'
    scrape_interval: 1m
    static_configs:
    - targets: ['localhost:9100']

  - job_name: 'blackbox'
    scrape_interval: 1m
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        # Update with real hostnames of your Beaker servers
        #- https://beaker.instance/
        #- lab-controller.instance
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115  # The blackbox exporter's real hostname:port.

  - job_name: 'beaker_abort_rate'
    metrics_path: /
    static_configs:
    - targets: ['localhost:8005']

  - job_name: 'beaker_availability'
    metrics_path: /
    static_configs:
    - targets: ['localhost:8000']

  - job_name: 'beaker_average_queue_time'
    scrape_timeout: 3m
    metrics_path: /metrics
    static_configs:
    - targets: ['localhost:8001']

  - job_name: 'beaker_broken_machines'
    metrics_path: /
    static_configs:
    - targets: ['localhost:8002']

  - job_name: 'beaker_command_status'
    metrics_path: /
    static_configs:
    - targets: ['localhost:8003']

  - job_name: 'beaker_active_users'
    metrics_path: /
    static_configs:
    - targets: ['localhost:8004']

  - job_name: 'beaker_lc_load'
    metrics_path: /
    static_configs:
    - targets: ['localhost:8006']

  - job_name: 'beaker_installation_time'
    metrics_path: /
    static_configs:
    - targets: ['localhost:8007']
